# Only build master and PRs against master
branches:
  only:
  - master
 
environment:
  matrix:
  - CONDA_PATH: "C:\\Miniconda37-x64"
    PYTHON_VERSION: 3.7
    ARCH: "64"

# No Visual Studio builds here
build: off

platform:
- x64

cache:
  - '%LOCALAPPDATA%\pip\Cache'
  - '%LOCALAPPDATA%\conda\conda\pkgs'

init:
  - ECHO "%CONDA_PATH%"

install:
- '"%CONDA_PATH%\\Scripts\\activate.bat"'
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- "conda env create -f environment-dev.yml"
- activate malstroem_dev

build_script:
  # Use build_ext --inplace otherwise pyinstaller does not pick up libraries
  - python setup.py build_ext --inplace

test_script:
  - pip install --no-dependencies -e .
  - pytest ./tests

after_test:
  - pyinstaller malstroem.spec
  - ps: ls dist
  # Check that malstroem.exe works
  - conda deactivate
  - ps: md test_outdir
  - ps: dist/malstroem complete -dem tests/data/dtm.tif -outdir test_outdir -mm 10

artifacts:
  - path: dist\*