name: malstroem_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - future
  - gdal
  - numpy
  - pip
  - pyinstaller
  - pytest
  - python=3.7
  - scipy
  - setuptools==44.0.0
  - pip:
    - click-log==0.1.8

