name: malstroem_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - cyarray
  - future
  - gdal <4.0
  - numpy <2.0
  - pip
  - pyinstaller
  - pytest
  - python
  - scipy
  - setuptools
  - sphinx_rtd_theme
  - numpydoc
  - tectonic
  - pip:
    - click-log==0.1.8

